from classes import String

play = String('PLAY', 'ИГРАТЬ')
settings = String('SETTINGS', 'НАСТРОЙКИ')
exit_ = String('EXIT', 'ВЫХОД')
start = String('START', 'НАЧАТЬ ИГРУ')
cancel = String('CANCEL', 'ОТМЕНА')
confirm = String('CONFIRM', 'ПОДТВЕРДИТЬ')
truth = String('TRUTH', 'ПРАВДА')
dare = String('DARE', 'ДЕЙСТВИЕ')
main_menu = String('MAIN MENU', 'ГЛАВНОЕ МЕНЮ')
continue_ = String('CONTINUE', 'ПРОДОЛЖИТЬ')
edit = String('EDIT', 'ИЗМЕНИТЬ')
delete = String('DELETE', 'УДАЛИТЬ')
lang = String('LANGUAGE', 'ЯЗЫК')
rules = String('RULES', 'ПРАВИЛА')
questions = String('QUESTIONS', 'ВОПРОСЫ')
tasks = String('TASKS', 'ЗАДАНИЯ')
back = String('BACK', 'НАЗАД')

player = String('PLAYER', 'ИГРОКА')
question = String('QUESTION', 'ВОПРОС')
task = String('TASK', 'ЗАДАНИЕ')

truth_dare = String('truth or dare?', 'правда или действие?')
title = String('TRUTH OR DARE', 'ПРАВДА ИЛИ ДЕЙСТВИЕ')
enter_player = String('Enter the name of player:', 'Введите имя игрока:')
enter_question = String('Enter the question:', 'Введите текст вопроса:')
enter_task = String('Enter the tasks:', 'Введите текст задания:')
del_confirm = String('DO YOU WANT TO DELETE', 'ВЫ ДЕЙСТВИТЕЛЬНО ХОТИТЕ УДАЛИТЬ')
add = String('ADD NEW', 'ДОБАВИТЬ')
